import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcryptjs";

export async function resetDatabase(client: PrismaClient) {
  await client.auditLog.deleteMany();
  await client.enrollment.deleteMany();
  await client.wishRequest.deleteMany();
  await client.studentResult.deleteMany();
  await client.section.deleteMany();
  await client.courseCondition.deleteMany();
  await client.registrationErrorCode.deleteMany();
  await client.systemSetting.deleteMany();
  await client.room.deleteMany();
  await client.course.deleteMany();
  await client.user.deleteMany();
  await client.semesterOption.deleteMany();
}

/* ──────────────────────── helpers ──────────────────────── */
interface CourseInput {
  code: string;
  name: string;
  credits: number;
  faculty: string;
  department: string;
  courseType: string;
  category: "FOUNDATION" | "CORE" | "ELECTIVE" | "THESIS";
  suggestedSemester: number;
  description: string;
  prerequisites?: string[];
}

const COURSE_TYPE_TO_BLOCK: Record<string, string> = {
  "Đại cương": "generalEducationCourses",
  "Cơ sở ngành": "foundationCourses",
  "Chuyên ngành": "majorCoreCourses",
  "Tự chọn": "electiveCourses",
  "Đồ án": "specializationCourses",
};

const FACULTY_TO_MAJOR: Record<string, string[]> = {
  "Công nghệ Thông tin": ["Công nghệ thông tin"],
  "An toàn Thông tin": ["An toàn thông tin"],
  "Viễn thông": ["Viễn thông"],
  "Điện tử": ["Điện tử"],
  "Đa phương tiện": ["Đa phương tiện"],
  "Quản trị Kinh doanh": ["Quản trị kinh doanh"],
  "Marketing": ["Marketing"],
  "Kế toán": ["Kế toán"],
};

const FACULTY_TO_MAJOR_CODE: Record<string, string[]> = {
  "Công nghệ Thông tin": ["7480201"],
  "An toàn Thông tin": ["7480202"],
  "Viễn thông": ["7480106"],
  "Điện tử": ["7510301"],
  "Đa phương tiện": ["7320104"],
  "Quản trị Kinh doanh": ["7340101"],
  "Marketing": ["7340115"],
  "Kế toán": ["7340301"],
};

/**
 * Tự động tính suggestedSemester từ mã môn (XX101 → 1, XX106 → 3, XX111 → 5, XX116 → 7).
 * 20 môn / ngành → 5 môn / semester × 4 semesters (1, 3, 5, 7).
 */
function computeSuggestedSemester(courseCode: string, fallback: number): number {
  const numMatch = courseCode.match(/(\d+)$/);
  if (!numMatch) return fallback;
  const num = Number(numMatch[1]);
  // num 101-105 → index 0 → semester 1
  // num 106-110 → index 1 → semester 3
  // num 111-115 → index 2 → semester 5
  // num 116-120 → index 3 → semester 7
  const indexInDept = (num % 100) - 1; // 0-19
  const semesterSlot = Math.floor(indexInDept / 5); // 0, 1, 2, 3
  return semesterSlot * 2 + 1; // 1, 3, 5, 7
}

function buildCourse(c: CourseInput) {
  return {
    id: `course-${c.code.toLowerCase()}`,
    code: c.code,
    name: c.name,
    credits: c.credits,
    status: "ACTIVE" as const,
    department: c.department,
    campus: "PTIT HCM",
    description: c.description,
    prerequisites: c.prerequisites ?? [],
    prestudy: [],
    corequisites: [],
    category: c.category,
    faculty: c.faculty,
    courseType: c.courseType,
    academicBlock: COURSE_TYPE_TO_BLOCK[c.courseType] ?? "electiveCourses",
    suggestedSemester: computeSuggestedSemester(c.code, c.suggestedSemester),
    majorsSupported: FACULTY_TO_MAJOR[c.faculty] ?? [c.faculty],
    majorCodesSupported: FACULTY_TO_MAJOR_CODE[c.faculty] ?? [],
  };
}

/* ──────────────────────── DATA: COURSES ──────────────────────── */
const ALL_COURSES: CourseInput[] = [
  {
    code: "INT101",
    name: "Giải tích",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Giải tích",
  },
  {
    code: "INT102",
    name: "Đại số",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Đại số",
  },
  {
    code: "INT103",
    name: "Toán rời rạc",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Toán rời rạc",
  },
  {
    code: "INT104",
    name: "Vật lý",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Vật lý",
  },
  {
    code: "INT105",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "INT106",
    name: "Lập trình C/C++",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình C/C++",
  },
  {
    code: "INT107",
    name: "Kỹ thuật số",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật số",
  },
  {
    code: "INT108",
    name: "Kiến trúc máy tính",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kiến trúc máy tính",
  },
  {
    code: "INT109",
    name: "Cấu trúc dữ liệu và giải thuật",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cấu trúc dữ liệu và giải thuật",
  },
  {
    code: "INT110",
    name: "Lập trình hướng đối tượng (OOP)",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình hướng đối tượng (OOP)",
  },
  {
    code: "INT111",
    name: "Cơ sở dữ liệu",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cơ sở dữ liệu",
  },
  {
    code: "INT112",
    name: "Mạng máy tính",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạng máy tính",
  },
  {
    code: "INT113",
    name: "Hệ điều hành",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hệ điều hành",
  },
  {
    code: "INT114",
    name: "Cơ sở an toàn thông tin",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cơ sở an toàn thông tin",
  },
  {
    code: "INT115",
    name: "Nhập môn Công nghệ phần mềm",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Nhập môn Công nghệ phần mềm",
  },
  {
    code: "INT116",
    name: "Hệ quản trị cơ sở dữ liệu",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hệ quản trị cơ sở dữ liệu",
  },
  {
    code: "INT117",
    name: "Phân tích thiết kế hệ thống thông tin",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Phân tích thiết kế hệ thống thông tin",
  },
  {
    code: "INT118",
    name: "Lập trình Web",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình Web",
  },
  {
    code: "INT119",
    name: "Nhập môn Trí tuệ nhân tạo",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Nhập môn Trí tuệ nhân tạo",
  },
  {
    code: "INT120",
    name: "Phát triển ứng dụng di động",
    credits: 3,
    faculty: "Công nghệ Thông tin",
    department: "INT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Phát triển ứng dụng di động",
  },
  {
    code: "SEC101",
    name: "Giải tích",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Giải tích",
  },
  {
    code: "SEC102",
    name: "Toán rời rạc",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Toán rời rạc",
  },
  {
    code: "SEC103",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "SEC104",
    name: "Lập trình C/C++",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình C/C++",
  },
  {
    code: "SEC105",
    name: "Cấu trúc dữ liệu và giải thuật",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cấu trúc dữ liệu và giải thuật",
  },
  {
    code: "SEC106",
    name: "Mạng máy tính",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạng máy tính",
  },
  {
    code: "SEC107",
    name: "Hệ điều hành",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hệ điều hành",
  },
  {
    code: "SEC108",
    name: "Kiến trúc máy tính",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kiến trúc máy tính",
  },
  {
    code: "SEC109",
    name: "Cơ sở dữ liệu",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cơ sở dữ liệu",
  },
  {
    code: "SEC110",
    name: "Cơ sở an toàn thông tin",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cơ sở an toàn thông tin",
  },
  {
    code: "SEC111",
    name: "Mật mã học",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mật mã học",
  },
  {
    code: "SEC112",
    name: "An toàn mạng máy tính",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "An toàn mạng máy tính",
  },
  {
    code: "SEC113",
    name: "An toàn hệ điều hành",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "An toàn hệ điều hành",
  },
  {
    code: "SEC114",
    name: "Phân tích mã độc",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Phân tích mã độc",
  },
  {
    code: "SEC115",
    name: "Lập trình an toàn",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình an toàn",
  },
  {
    code: "SEC116",
    name: "Đánh giá an toàn hệ thống thông tin",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Đánh giá an toàn hệ thống thông tin",
  },
  {
    code: "SEC117",
    name: "Quản lý rủi ro an toàn thông tin",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản lý rủi ro an toàn thông tin",
  },
  {
    code: "SEC118",
    name: "Kỹ thuật dịch ngược (Reverse Engineering)",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật dịch ngược (Reverse Engineering)",
  },
  {
    code: "SEC119",
    name: "Pháp luật và đạo đức về ATTT",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật và đạo đức về ATTT",
  },
  {
    code: "SEC120",
    name: "Điều tra số (Digital Forensics)",
    credits: 3,
    faculty: "An toàn Thông tin",
    department: "SEC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Điều tra số (Digital Forensics)",
  },
  {
    code: "TEL101",
    name: "Giải tích",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Giải tích",
  },
  {
    code: "TEL102",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "TEL103",
    name: "Lập trình C/C++",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình C/C++",
  },
  {
    code: "TEL104",
    name: "Kỹ thuật số",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật số",
  },
  {
    code: "TEL105",
    name: "Lý thuyết mạch",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lý thuyết mạch",
  },
  {
    code: "TEL106",
    name: "Tín hiệu và hệ thống",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Tín hiệu và hệ thống",
  },
  {
    code: "TEL107",
    name: "Điện tử tương tự",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Điện tử tương tự",
  },
  {
    code: "TEL108",
    name: "Trường điện từ",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Trường điện từ",
  },
  {
    code: "TEL109",
    name: "Kỹ thuật vi xử lý",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật vi xử lý",
  },
  {
    code: "TEL110",
    name: "Cơ sở kỹ thuật thông tin",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cơ sở kỹ thuật thông tin",
  },
  {
    code: "TEL111",
    name: "Mạng viễn thông",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạng viễn thông",
  },
  {
    code: "TEL112",
    name: "Kỹ thuật chuyển mạch",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật chuyển mạch",
  },
  {
    code: "TEL113",
    name: "Kỹ thuật truyền dẫn quang",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật truyền dẫn quang",
  },
  {
    code: "TEL114",
    name: "Thông tin di động (4G/5G)",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thông tin di động (4G/5G)",
  },
  {
    code: "TEL115",
    name: "Anten và truyền sóng",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Anten và truyền sóng",
  },
  {
    code: "TEL116",
    name: "Kỹ thuật siêu cao tần",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật siêu cao tần",
  },
  {
    code: "TEL117",
    name: "Thông tin vệ tinh",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thông tin vệ tinh",
  },
  {
    code: "TEL118",
    name: "Xử lý tín hiệu số",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Xử lý tín hiệu số",
  },
  {
    code: "TEL119",
    name: "Thiết kế mạng vô tuyến",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thiết kế mạng vô tuyến",
  },
  {
    code: "TEL120",
    name: "Mạng Internet vạn vật (IoT)",
    credits: 3,
    faculty: "Viễn thông",
    department: "TEL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạng Internet vạn vật (IoT)",
  },
  {
    code: "ELE101",
    name: "Giải tích",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Giải tích",
  },
  {
    code: "ELE102",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "ELE103",
    name: "Lập trình C/C++",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình C/C++",
  },
  {
    code: "ELE104",
    name: "Kỹ thuật số",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật số",
  },
  {
    code: "ELE105",
    name: "Cấu kiện điện tử",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cấu kiện điện tử",
  },
  {
    code: "ELE106",
    name: "Lý thuyết mạch",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lý thuyết mạch",
  },
  {
    code: "ELE107",
    name: "Mạch điện tử",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạch điện tử",
  },
  {
    code: "ELE108",
    name: "Đo lường điện tử",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Đo lường điện tử",
  },
  {
    code: "ELE109",
    name: "Tín hiệu và hệ thống",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Tín hiệu và hệ thống",
  },
  {
    code: "ELE110",
    name: "Kỹ thuật vi xử lý / Vi điều khiển",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ thuật vi xử lý / Vi điều khiển",
  },
  {
    code: "ELE111",
    name: "Hệ thống nhúng (Embedded Systems)",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hệ thống nhúng (Embedded Systems)",
  },
  {
    code: "ELE112",
    name: "Thiết kế vi mạch số (VLSI)",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thiết kế vi mạch số (VLSI)",
  },
  {
    code: "ELE113",
    name: "Điện tử công suất",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Điện tử công suất",
  },
  {
    code: "ELE114",
    name: "Cảm biến và ứng dụng",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cảm biến và ứng dụng",
  },
  {
    code: "ELE115",
    name: "Điều khiển tự động / PLC",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Điều khiển tự động / PLC",
  },
  {
    code: "ELE116",
    name: "Giao tiếp máy tính",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Giao tiếp máy tính",
  },
  {
    code: "ELE117",
    name: "Xử lý tín hiệu số trong hệ thống điện tử",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Xử lý tín hiệu số trong hệ thống điện tử",
  },
  {
    code: "ELE118",
    name: "Robot và trí tuệ nhân tạo trong điện tử",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Robot và trí tuệ nhân tạo trong điện tử",
  },
  {
    code: "ELE119",
    name: "Cơ sở kỹ thuật truyền hình",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cơ sở kỹ thuật truyền hình",
  },
  {
    code: "ELE120",
    name: "Mạng truyền số liệu",
    credits: 3,
    faculty: "Điện tử",
    department: "ELE",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạng truyền số liệu",
  },
  {
    code: "MUL101",
    name: "Giải tích",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Giải tích",
  },
  {
    code: "MUL102",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "MUL103",
    name: "Mỹ thuật cơ bản (Vẽ tay/Bố cục)",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mỹ thuật cơ bản (Vẽ tay/Bố cục)",
  },
  {
    code: "MUL104",
    name: "Lập trình C/C++",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình C/C++",
  },
  {
    code: "MUL105",
    name: "Nguyên lý thiết kế đa phương tiện",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Nguyên lý thiết kế đa phương tiện",
  },
  {
    code: "MUL106",
    name: "Kịch bản đa phương tiện",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kịch bản đa phương tiện",
  },
  {
    code: "MUL107",
    name: "Cấu trúc dữ liệu và giải thuật",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Cấu trúc dữ liệu và giải thuật",
  },
  {
    code: "MUL108",
    name: "Mạng máy tính & CSDL",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Cơ sở ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Mạng máy tính & CSDL",
  },
  {
    code: "MUL109",
    name: "Đồ họa máy tính",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Đồ họa máy tính",
  },
  {
    code: "MUL110",
    name: "Xử lý ảnh số (Photoshop/Illustrator)",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Xử lý ảnh số (Photoshop/Illustrator)",
  },
  {
    code: "MUL111",
    name: "Xử lý âm thanh và video (Premiere/After Effects)",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Xử lý âm thanh và video (Premiere/After Effects)",
  },
  {
    code: "MUL112",
    name: "Thiết kế giao diện người dùng (UI/UX)",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thiết kế giao diện người dùng (UI/UX)",
  },
  {
    code: "MUL113",
    name: "Lập trình Web",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình Web",
  },
  {
    code: "MUL114",
    name: "Lập trình ứng dụng di động",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình ứng dụng di động",
  },
  {
    code: "MUL115",
    name: "Kỹ xảo hình ảnh (VFX)",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kỹ xảo hình ảnh (VFX)",
  },
  {
    code: "MUL116",
    name: "Lập trình phát triển Game",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Lập trình phát triển Game",
  },
  {
    code: "MUL117",
    name: "Đồ họa 3D (Maya/Blender)",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Đồ họa 3D (Maya/Blender)",
  },
  {
    code: "MUL118",
    name: "Thiết kế sản phẩm đa phương tiện",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thiết kế sản phẩm đa phương tiện",
  },
  {
    code: "MUL119",
    name: "Sản xuất chương trình truyền hình",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Sản xuất chương trình truyền hình",
  },
  {
    code: "MUL120",
    name: "Truyền thông đa phương tiện",
    credits: 3,
    faculty: "Đa phương tiện",
    department: "MUL",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Truyền thông đa phương tiện",
  },
  {
    code: "BUS101",
    name: "Toán cao cấp",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Toán cao cấp",
  },
  {
    code: "BUS102",
    name: "Pháp luật đại cương",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật đại cương",
  },
  {
    code: "BUS103",
    name: "Lịch sử Đảng",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Lịch sử Đảng",
  },
  {
    code: "BUS104",
    name: "Kinh tế vi mô",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kinh tế vi mô",
  },
  {
    code: "BUS105",
    name: "Kinh tế vĩ mô",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kinh tế vĩ mô",
  },
  {
    code: "BUS106",
    name: "Nguyên lý kế toán",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Nguyên lý kế toán",
  },
  {
    code: "BUS107",
    name: "Quản trị học",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị học",
  },
  {
    code: "BUS108",
    name: "Marketing căn bản",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Marketing căn bản",
  },
  {
    code: "BUS109",
    name: "Hệ thống thông tin quản lý",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hệ thống thông tin quản lý",
  },
  {
    code: "BUS110",
    name: "Hành vi tổ chức",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hành vi tổ chức",
  },
  {
    code: "BUS111",
    name: "Quản trị nguồn nhân lực",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị nguồn nhân lực",
  },
  {
    code: "BUS112",
    name: "Quản trị sản xuất và tác nghiệp",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị sản xuất và tác nghiệp",
  },
  {
    code: "BUS113",
    name: "Quản trị tài chính",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị tài chính",
  },
  {
    code: "BUS114",
    name: "Quản trị chiến lược",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị chiến lược",
  },
  {
    code: "BUS115",
    name: "Giao tiếp trong kinh doanh",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Giao tiếp trong kinh doanh",
  },
  {
    code: "BUS116",
    name: "Thương mại điện tử",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thương mại điện tử",
  },
  {
    code: "BUS117",
    name: "Khởi sự kinh doanh (Startup)",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Khởi sự kinh doanh (Startup)",
  },
  {
    code: "BUS118",
    name: "Quản trị rủi ro",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị rủi ro",
  },
  {
    code: "BUS119",
    name: "Quản trị chất lượng",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị chất lượng",
  },
  {
    code: "BUS120",
    name: "Phân tích hoạt động kinh doanh",
    credits: 3,
    faculty: "Quản trị Kinh doanh",
    department: "BUS",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Phân tích hoạt động kinh doanh",
  },
  {
    code: "MKT101",
    name: "Toán cao cấp",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Toán cao cấp",
  },
  {
    code: "MKT102",
    name: "Lịch sử Đảng",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Lịch sử Đảng",
  },
  {
    code: "MKT103",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "MKT104",
    name: "Kinh tế vi mô & Vĩ mô",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kinh tế vi mô & Vĩ mô",
  },
  {
    code: "MKT105",
    name: "Nguyên lý kế toán",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Nguyên lý kế toán",
  },
  {
    code: "MKT106",
    name: "Quản trị học",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị học",
  },
  {
    code: "MKT107",
    name: "Marketing căn bản",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Marketing căn bản",
  },
  {
    code: "MKT108",
    name: "Hành vi người tiêu dùng",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Hành vi người tiêu dùng",
  },
  {
    code: "MKT109",
    name: "Nghiên cứu Marketing",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Nghiên cứu Marketing",
  },
  {
    code: "MKT110",
    name: "Marketing dịch vụ",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Marketing dịch vụ",
  },
  {
    code: "MKT111",
    name: "Marketing quốc tế",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Marketing quốc tế",
  },
  {
    code: "MKT112",
    name: "Quản trị thương hiệu",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị thương hiệu",
  },
  {
    code: "MKT113",
    name: "Truyền thông Marketing tích hợp (IMC)",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Truyền thông Marketing tích hợp (IMC)",
  },
  {
    code: "MKT114",
    name: "Digital Marketing (Tiếp thị số)",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Digital Marketing (Tiếp thị số)",
  },
  {
    code: "MKT115",
    name: "Quan hệ công chúng (PR)",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quan hệ công chúng (PR)",
  },
  {
    code: "MKT116",
    name: "Tổ chức sự kiện",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Tổ chức sự kiện",
  },
  {
    code: "MKT117",
    name: "Quản trị lực lượng bán hàng",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị lực lượng bán hàng",
  },
  {
    code: "MKT118",
    name: "Quản trị kênh phân phối",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị kênh phân phối",
  },
  {
    code: "MKT119",
    name: "Phân tích dữ liệu Marketing",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Phân tích dữ liệu Marketing",
  },
  {
    code: "MKT120",
    name: "Content Marketing (Tiếp thị nội dung)",
    credits: 3,
    faculty: "Marketing",
    department: "MKT",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Content Marketing (Tiếp thị nội dung)",
  },
  {
    code: "ACC101",
    name: "Toán cao cấp",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Toán cao cấp",
  },
  {
    code: "ACC102",
    name: "Lịch sử Đảng",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Lịch sử Đảng",
  },
  {
    code: "ACC103",
    name: "Pháp luật Đại cương",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Pháp luật Đại cương",
  },
  {
    code: "ACC104",
    name: "Kinh tế vi mô",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Kinh tế vi mô",
  },
  {
    code: "ACC105",
    name: "Quản trị học",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Quản trị học",
  },
  {
    code: "ACC106",
    name: "Tài chính tiền tệ",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Tài chính tiền tệ",
  },
  {
    code: "ACC107",
    name: "Nguyên lý kế toán",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Nguyên lý kế toán",
  },
  {
    code: "ACC108",
    name: "Kế toán tài chính",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán tài chính",
  },
  {
    code: "ACC109",
    name: "Kế toán quản trị",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán quản trị",
  },
  {
    code: "ACC110",
    name: "Kiểm toán căn bản",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kiểm toán căn bản",
  },
  {
    code: "ACC111",
    name: "Kế toán chi phí",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán chi phí",
  },
  {
    code: "ACC112",
    name: "Hệ thống thông tin kế toán",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Hệ thống thông tin kế toán",
  },
  {
    code: "ACC113",
    name: "Tổ chức công tác kế toán",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Tổ chức công tác kế toán",
  },
  {
    code: "ACC114",
    name: "Kế toán máy (Thực hành phần mềm MISA/ERP)",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán máy (Thực hành phần mềm MISA/ERP)",
  },
  {
    code: "ACC115",
    name: "Phân tích báo cáo tài chính",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Phân tích báo cáo tài chính",
  },
  {
    code: "ACC116",
    name: "Kế toán thuế",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán thuế",
  },
  {
    code: "ACC117",
    name: "Kế toán ngân hàng",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán ngân hàng",
  },
  {
    code: "ACC118",
    name: "Kế toán công ty cổ phần",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kế toán công ty cổ phần",
  },
  {
    code: "ACC119",
    name: "Kiểm toán báo cáo tài chính",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Đại cương",
    category: "FOUNDATION",
    suggestedSemester: 1,
    description: "Kiểm toán báo cáo tài chính",
  },
  {
    code: "ACC120",
    name: "Thị trường chứng khoán",
    credits: 3,
    faculty: "Kế toán",
    department: "ACC",
    courseType: "Chuyên ngành",
    category: "CORE",
    suggestedSemester: 1,
    description: "Thị trường chứng khoán",
  },
];

/* ──────────────────────── DATA: ROOMS ──────────────────────── */
const ROOMS = [
  {
    id: "room-a1-101",
    code: "A1-101",
    name: "A1-101",
    capacity: 40,
    campus: "PTIT HCM",
  },
  {
    id: "room-a1-201",
    code: "A1-201",
    name: "A1-201",
    capacity: 45,
    campus: "PTIT HCM",
  },
  {
    id: "room-a1-202",
    code: "A1-202",
    name: "A1-202",
    capacity: 45,
    campus: "PTIT HCM",
  },
  {
    id: "room-a1-301",
    code: "A1-301",
    name: "A1-301",
    capacity: 50,
    campus: "PTIT HCM",
  },
  {
    id: "room-a1-302",
    code: "A1-302",
    name: "A1-302",
    capacity: 50,
    campus: "PTIT HCM",
  },
  {
    id: "room-a2-101",
    code: "A2-101",
    name: "A2-101",
    capacity: 40,
    campus: "PTIT HCM",
  },
  {
    id: "room-a2-201",
    code: "A2-201",
    name: "A2-201",
    capacity: 45,
    campus: "PTIT HCM",
  },
  {
    id: "room-a2-301",
    code: "A2-301",
    name: "A2-301",
    capacity: 50,
    campus: "PTIT HCM",
  },
  {
    id: "room-b1-101",
    code: "B1-101",
    name: "B1-101",
    capacity: 40,
    campus: "PTIT HCM",
  },
  {
    id: "room-b1-201",
    code: "B1-201",
    name: "B1-201",
    capacity: 45,
    campus: "PTIT HCM",
  },
  {
    id: "room-b1-301",
    code: "B1-301",
    name: "B1-301",
    capacity: 50,
    campus: "PTIT HCM",
  },
  {
    id: "room-c1-101",
    code: "C1-101",
    name: "C1-101",
    capacity: 60,
    campus: "PTIT HCM",
  },
  {
    id: "room-c1-201",
    code: "C1-201",
    name: "C1-201",
    capacity: 60,
    campus: "PTIT HCM",
  },
  {
    id: "room-c1-301",
    code: "C1-301",
    name: "C1-301",
    capacity: 80,
    campus: "PTIT HCM",
  },
];

/* ──────────────────────── MAIN SEED ──────────────────────── */
export async function seedDemoData(
  client: PrismaClient,
  options: { reset?: boolean } = {},
) {
  if (options.reset ?? true) {
    await resetDatabase(client);
  }

  const passwordDigest = await bcrypt.hash("ptithcm2026", 10);
  const currentSemesterId = "sem-2026-1";
  const previousSemesterId = "sem-2025-2";

  /* ── Semesters ── */
  await client.semesterOption.createMany({
    data: [
      {
        id: previousSemesterId,
        label: "Học kỳ 2025-2",
        isCurrent: false,
        academicYear: "2025-2026",
        termCode: "HK2",
        registrationStatus: "COMPLETED",
      },
      {
        id: currentSemesterId,
        label: "Học kỳ 2026-1",
        isCurrent: true,
        academicYear: "2026-2027",
        termCode: "HK1",
        registrationStatus: "OPEN",
        registrationStart: new Date("2026-04-01T00:00:00.000Z"),
        registrationEnd: new Date("2026-04-30T23:59:59.999Z"),
        adjustmentStart: new Date("2026-05-01T00:00:00.000Z"),
        adjustmentEnd: new Date("2026-05-10T23:59:59.999Z"),
      },
      {
        id: "sem-2026-he",
        label: "Học kỳ hè 2026",
        type: "SUMMER",
        isCurrent: false,
        academicYear: "2026-2027",
        termCode: "HÈ",
        registrationStatus: "UPCOMING",
        registrationStart: new Date("2026-06-01T00:00:00.000Z"),
        registrationEnd: new Date("2026-06-15T23:59:59.999Z"),
        adjustmentStart: new Date("2026-06-16T00:00:00.000Z"),
        adjustmentEnd: new Date("2026-06-20T23:59:59.999Z"),
      },
    ],
  });

  /* ── Users ── */
  await client.user.createMany({
    data: [
      // Admin & Academic Office
      {
        id: "AD001",
        code: "AD001",
        username: "admin",
        email: "admin@ptithcm.edu.vn",
        fullName: "Quản trị hệ thống",
        phone: "0900000001",
        roles: ["ADMIN"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "IT",
        passwordDigest,
      },
      {
        id: "AO001",
        code: "AO001",
        username: "academic.office",
        email: "academic.office@ptithcm.edu.vn",
        fullName: "Phòng đào tạo",
        phone: "0900000002",
        roles: ["ACADEMIC_OFFICE"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "Academic Office",
        passwordDigest,
      },

      // Lecturers — CNTT
      {
        id: "LEC001",
        code: "LEC001",
        username: "minh.tuan",
        email: "minh.tuan@ptithcm.edu.vn",
        fullName: "Nguyễn Minh Tuấn",
        phone: "0900000003",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "CNTT",
        faculty: "Công nghệ thông tin",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Công nghệ phần mềm",
        passwordDigest,
      },
      {
        id: "LEC002",
        code: "LEC002",
        username: "thu.ha",
        email: "thu.ha@ptithcm.edu.vn",
        fullName: "Trần Thu Hà",
        phone: "0900000004",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "CNTT",
        faculty: "Công nghệ thông tin",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Hệ thống thông tin",
        passwordDigest,
      },
      {
        id: "LEC017",
        code: "LEC017",
        username: "quang.vinh",
        email: "quang.vinh@ptithcm.edu.vn",
        fullName: "Ngô Quang Vinh",
        phone: "0900000019",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "CNTT",
        faculty: "Công nghệ thông tin",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Trí tuệ nhân tạo",
        passwordDigest,
      },
      {
        id: "LEC018",
        code: "LEC018",
        username: "thi.huong",
        email: "thi.huong@ptithcm.edu.vn",
        fullName: "Đinh Thị Hương",
        phone: "0900000020",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "CNTT",
        faculty: "Công nghệ thông tin",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Lập trình Web",
        passwordDigest,
      },
      // Lecturers — ATTT
      {
        id: "LEC003",
        code: "LEC003",
        username: "quoc.huy",
        email: "quoc.huy@ptithcm.edu.vn",
        fullName: "Phạm Quốc Huy",
        phone: "0900000005",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "ATTT",
        faculty: "An toàn thông tin",
        title: "TS.",
        position: "Giảng viên",
        specialization: "An toàn mạng",
        passwordDigest,
      },
      {
        id: "LEC004",
        code: "LEC004",
        username: "thi.lan",
        email: "thi.lan@ptithcm.edu.vn",
        fullName: "Vũ Thị Lan",
        phone: "0900000006",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "ATTT",
        faculty: "An toàn thông tin",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Mật mã học",
        passwordDigest,
      },
      // Lecturers — Viễn thông
      {
        id: "LEC005",
        code: "LEC005",
        username: "duc.minh",
        email: "duc.minh@ptithcm.edu.vn",
        fullName: "Hoàng Đức Minh",
        phone: "0900000007",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "VT",
        faculty: "Viễn thông",
        title: "PGS.TS.",
        position: "Phó trưởng khoa",
        specialization: "Hệ thống viễn thông",
        passwordDigest,
      },
      {
        id: "LEC006",
        code: "LEC006",
        username: "thanh.tung",
        email: "thanh.tung@ptithcm.edu.vn",
        fullName: "Đỗ Thanh Tùng",
        phone: "0900000008",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "VT",
        faculty: "Viễn thông",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Thông tin di động",
        passwordDigest,
      },
      // Lecturers — Điện tử
      {
        id: "LEC007",
        code: "LEC007",
        username: "hong.phuc",
        email: "hong.phuc@ptithcm.edu.vn",
        fullName: "Lê Hồng Phúc",
        phone: "0900000009",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "DT",
        faculty: "Điện tử",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Vi mạch số",
        passwordDigest,
      },
      {
        id: "LEC008",
        code: "LEC008",
        username: "thi.mai",
        email: "thi.mai@ptithcm.edu.vn",
        fullName: "Nguyễn Thị Mai",
        phone: "0900000010",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "DT",
        faculty: "Điện tử",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Hệ thống nhúng",
        passwordDigest,
      },
      // Lecturers — Đa phương tiện
      {
        id: "LEC009",
        code: "LEC009",
        username: "van.dat",
        email: "van.dat@ptithcm.edu.vn",
        fullName: "Trương Văn Đạt",
        phone: "0900000011",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "DPT",
        faculty: "Đa phương tiện",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Đồ họa máy tính",
        passwordDigest,
      },
      {
        id: "LEC010",
        code: "LEC010",
        username: "ngoc.diep",
        email: "ngoc.diep@ptithcm.edu.vn",
        fullName: "Phan Ngọc Diệp",
        phone: "0900000012",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "DPT",
        faculty: "Đa phương tiện",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "UI/UX Design",
        passwordDigest,
      },
      // Lecturers — QTKD
      {
        id: "LEC011",
        code: "LEC011",
        username: "minh.tri",
        email: "minh.tri@ptithcm.edu.vn",
        fullName: "Bùi Minh Trí",
        phone: "0900000013",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "QTKD",
        faculty: "Quản trị kinh doanh",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Quản trị chiến lược",
        passwordDigest,
      },
      {
        id: "LEC012",
        code: "LEC012",
        username: "thi.hong",
        email: "thi.hong@ptithcm.edu.vn",
        fullName: "Cao Thị Hồng",
        phone: "0900000014",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "QTKD",
        faculty: "Quản trị kinh doanh",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Marketing",
        passwordDigest,
      },
      // Lecturers — Marketing
      {
        id: "LEC013",
        code: "LEC013",
        username: "anh.khoa",
        email: "anh.khoa@ptithcm.edu.vn",
        fullName: "Đặng Anh Khoa",
        phone: "0900000015",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "MKT",
        faculty: "Marketing",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Digital Marketing",
        passwordDigest,
      },
      {
        id: "LEC014",
        code: "LEC014",
        username: "thi.thanh",
        email: "thi.thanh@ptithcm.edu.vn",
        fullName: "Lý Thị Thanh",
        phone: "0900000016",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "MKT",
        faculty: "Marketing",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Truyền thông",
        passwordDigest,
      },
      // Lecturers — Kế toán
      {
        id: "LEC015",
        code: "LEC015",
        username: "xuan.bach",
        email: "xuan.bach@ptithcm.edu.vn",
        fullName: "Mai Xuân Bách",
        phone: "0900000017",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "KT",
        faculty: "Kế toán",
        title: "TS.",
        position: "Giảng viên",
        specialization: "Kế toán tài chính",
        passwordDigest,
      },
      {
        id: "LEC016",
        code: "LEC016",
        username: "kim.oanh",
        email: "kim.oanh@ptithcm.edu.vn",
        fullName: "Tạ Thị Kim Oanh",
        phone: "0900000018",
        roles: ["LECTURER"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "KT",
        faculty: "Kế toán",
        title: "ThS.",
        position: "Giảng viên",
        specialization: "Kiểm toán",
        passwordDigest,
      },

      // Students
      {
        id: "N23DCCN001",
        code: "N23DCCN001",
        username: "N23DCCN001",
        email: "n23dccn001@student.ptithcm.edu.vn",
        fullName: "Nguyễn Văn An",
        phone: "0911000001",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "CNTT",
        faculty: "Công nghệ thông tin",
        majorCode: "DCCN",
        majorName: "Công nghệ phần mềm",
        studentClass: "D23CQCN01-N",
        studentStatus: "Đang học",
        completedCredits: 24,
        gpa: 3.2,
        passwordDigest,
      },
      {
        id: "N23DCCN002",
        code: "N23DCCN002",
        username: "N23DCCN002",
        email: "n23dccn002@student.ptithcm.edu.vn",
        fullName: "Lê Thị Bình",
        phone: "0911000002",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "CNTT",
        faculty: "Công nghệ thông tin",
        majorCode: "DCCN",
        majorName: "Công nghệ phần mềm",
        studentClass: "D23CQCN01-N",
        studentStatus: "Đang học",
        completedCredits: 18,
        gpa: 3.0,
        passwordDigest,
      },
      {
        id: "N23DCAT001",
        code: "N23DCAT001",
        username: "N23DCAT001",
        email: "n23dcat001@student.ptithcm.edu.vn",
        fullName: "Trần Đức Cường",
        phone: "0911000003",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "ATTT",
        faculty: "An toàn thông tin",
        majorCode: "DCAT",
        majorName: "An toàn thông tin",
        studentClass: "D23CQAT01-N",
        studentStatus: "Đang học",
        completedCredits: 22,
        gpa: 3.4,
        passwordDigest,
      },
      {
        id: "N23DCVT001",
        code: "N23DCVT001",
        username: "N23DCVT001",
        email: "n23dcvt001@student.ptithcm.edu.vn",
        fullName: "Phạm Thanh Dũng",
        phone: "0911000004",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "VT",
        faculty: "Viễn thông",
        majorCode: "DCVT",
        majorName: "Kỹ thuật viễn thông",
        studentClass: "D23CQVT01-N",
        studentStatus: "Đang học",
        completedCredits: 20,
        gpa: 2.8,
        passwordDigest,
      },
      {
        id: "N23DCDT001",
        code: "N23DCDT001",
        username: "N23DCDT001",
        email: "n23dcdt001@student.ptithcm.edu.vn",
        fullName: "Hoàng Mai Linh",
        phone: "0911000005",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "DT",
        faculty: "Điện tử",
        majorCode: "DCDT",
        majorName: "Kỹ thuật điện tử",
        studentClass: "D23CQDT01-N",
        studentStatus: "Đang học",
        completedCredits: 21,
        gpa: 3.1,
        passwordDigest,
      },
      {
        id: "N24DCPT001",
        code: "N24DCPT001",
        username: "N24DCPT001",
        email: "n24dcpt001@student.ptithcm.edu.vn",
        fullName: "Vũ Quỳnh Anh",
        phone: "0911000006",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "DPT",
        faculty: "Đa phương tiện",
        majorCode: "DCPT",
        majorName: "Công nghệ đa phương tiện",
        studentClass: "D24CQPT01-N",
        studentStatus: "Đang học",
        completedCredits: 12,
        gpa: 3.5,
        passwordDigest,
      },
      {
        id: "N24DCQT001",
        code: "N24DCQT001",
        username: "N24DCQT001",
        email: "n24dcqt001@student.ptithcm.edu.vn",
        fullName: "Đỗ Minh Khôi",
        phone: "0911000007",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "QTKD",
        faculty: "Quản trị kinh doanh",
        majorCode: "DCQT",
        majorName: "Quản trị kinh doanh",
        studentClass: "D24CQQT01-N",
        studentStatus: "Đang học",
        completedCredits: 15,
        gpa: 3.3,
        passwordDigest,
      },
      {
        id: "N24DCMR001",
        code: "N24DCMR001",
        username: "N24DCMR001",
        email: "n24dcmr001@student.ptithcm.edu.vn",
        fullName: "Nguyễn Hà My",
        phone: "0911000008",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "MKT",
        faculty: "Marketing",
        majorCode: "DCMR",
        majorName: "Marketing",
        studentClass: "D24CQMR01-N",
        studentStatus: "Đang học",
        completedCredits: 14,
        gpa: 3.6,
        passwordDigest,
      },
      {
        id: "N24DCKT001",
        code: "N24DCKT001",
        username: "N24DCKT001",
        email: "n24dckt001@student.ptithcm.edu.vn",
        fullName: "Lê Thanh Sơn",
        phone: "0911000009",
        roles: ["STUDENT"],
        status: "ACTIVE",
        campus: "PTIT HCM",
        department: "KT",
        faculty: "Kế toán",
        majorCode: "DCKT",
        majorName: "Kế toán",
        studentClass: "D24CQKT01-N",
        studentStatus: "Đang học",
        completedCredits: 13,
        gpa: 3.1,
        passwordDigest,
      },
    ],
  });

  /* ── Courses (160) ── */
  await client.course.createMany({ data: ALL_COURSES.map(buildCourse) });

  /* ── Rooms (14) ── */
  await client.room.createMany({ data: ROOMS });

  /* ── Registration Error Codes ── */
  await client.registrationErrorCode.createMany({
    data: [
      { code: "DK_TC", message: "Đăng ký thành công." },
      { code: "HUY_DK", message: "Đã hủy đăng ký." },
      { code: "KHONG_DU_DK", message: "Không đủ điều kiện đăng ký." },
      { code: "NGOAI_TGDK", message: "Ngoài thời gian đăng ký." },
      {
        code: "REG_ERR_SECTION_NOT_OPEN",
        message: "Lớp học phần chưa mở đăng ký.",
      },
      {
        code: "REG_ERR_OUTSIDE_REGISTRATION_WINDOW",
        message: "Ngoài thời gian đăng ký.",
      },
      {
        code: "REG_ERR_OUTSIDE_ADJUSTMENT_WINDOW",
        message: "Ngoài thời gian điều chỉnh đăng ký.",
      },
      { code: "REG_ERR_FULL_CAPACITY", message: "Lớp học phần đã đủ sĩ số." },
      {
        code: "REG_ERR_PREREQUISITE_NOT_MET",
        message: "Chưa đạt môn tiên quyết.",
      },
      {
        code: "REG_ERR_PRESTUDY_NOT_MET",
        message: "Chưa đáp ứng môn học trước.",
      },
      {
        code: "REG_ERR_COREQUISITE_NOT_MET",
        message: "Chưa đáp ứng môn song hành.",
      },
      { code: "REG_ERR_SCHEDULE_CONFLICT", message: "Trùng thời khóa biểu." },
      {
        code: "REG_ERR_CREDIT_LIMIT_EXCEEDED",
        message: "Vượt giới hạn tín chỉ.",
      },
      {
        code: "REG_ERR_ALREADY_REGISTERED",
        message: "Đã đăng ký lớp học phần này.",
      },
      {
        code: "REG_ERR_ALREADY_REGISTERED_COURSE",
        message:
          "Đã đăng ký hoặc vào danh sách chờ lớp khác của cùng học phần trong học kỳ này.",
      },
      {
        code: "REG_ERR_CLASS_NOT_FOUND",
        message: "Không tìm thấy lớp học phần.",
      },
      {
        code: "REG_ERR_STUDENT_NOT_FOUND",
        message: "Không tìm thấy sinh viên.",
      },
      { code: "REG_ERR_CLASS_CANCELLED", message: "Lớp học phần đã bị hủy." },
      {
        code: "REG_ERR_ACCOUNT_INACTIVE",
        message: "Tài khoản không hoạt động.",
      },
      {
        code: "REG_ERR_MAX_CLASS_PER_DAY",
        message: "Vượt số lớp tối đa trong ngày.",
      },
      {
        code: "REG_ERR_MAX_CLASS_PER_SEMESTER",
        message: "Vượt số lớp tối đa trong học kỳ.",
      },
    ],
  });

  /* ── Sections (1 per course for current semester) ── */
  const lecturerByDept: Record<string, string[]> = {
    // New department codes used in ALL_COURSES
    INT: ["LEC001", "LEC002", "LEC017", "LEC018"],
    SEC: ["LEC003", "LEC004"],
    TEL: ["LEC005", "LEC006"],
    ELE: ["LEC007", "LEC008"],
    MUL: ["LEC009", "LEC010"],
    BUS: ["LEC011", "LEC012"],
    MKT: ["LEC013", "LEC014"],
    ACC: ["LEC015", "LEC016"],
    // Legacy department codes (keep for backward compat)
    CNTT: ["LEC001", "LEC002", "LEC017", "LEC018"],
    ATTT: ["LEC003", "LEC004"],
    VT: ["LEC005", "LEC006"],
    DT: ["LEC007", "LEC008"],
    DPT: ["LEC009", "LEC010"],
    QTKD: ["LEC011", "LEC012"],
    KT: ["LEC015", "LEC016"],
    // Catch-all for shared/misc departments
    IT: ["LEC001", "LEC002", "LEC017", "LEC018"],
    "Academic Office": ["LEC001", "LEC002"],
  };

  // --- Conflict-free schedule generation ---
  // 3 non-overlapping time blocks per day: startPeriod 1 (Ca sáng), 5 (Ca chiều), 9 (Ca tối)
  // 6 weekdays (Mon–Sat, encoded 2–7) × 3 blocks = 18 slots per lecturer / room
  // 14 rooms × 18 slots = 252 total capacity (>160 courses)
  const WEEKDAYS = [2, 3, 4, 5, 6, 7];
  const PERIOD_SLOTS = [1, 5, 9];

  type SlotEntry = {
    weekday: number;
    startPeriod: number;
    periodCount: number;
  };

  function scheduleConflicts(
    schedule: SlotEntry[],
    weekday: number,
    startPeriod: number,
    periodCount: number,
  ): boolean {
    return schedule.some(
      (s) =>
        s.weekday === weekday &&
        s.startPeriod < startPeriod + periodCount &&
        startPeriod < s.startPeriod + s.periodCount,
    );
  }

  const lecturerSchedule = new Map<string, SlotEntry[]>();
  const roomSchedule = new Map<string, SlotEntry[]>();

  const sectionData = ALL_COURSES.map((course, index) => {
    const lecturers = lecturerByDept[course.department] ?? ["LEC001"];
    const lecturerId = lecturers[index % lecturers.length];
    const periodCount = course.credits >= 4 ? 4 : 3;

    if (!lecturerSchedule.has(lecturerId)) lecturerSchedule.set(lecturerId, []);
    const lecSched = lecturerSchedule.get(lecturerId)!;

    let weekday = WEEKDAYS[0];
    let startPeriod = PERIOD_SLOTS[0];
    let roomObj = ROOMS[0];

    // Find first (weekday, timeSlot, room) with no lecturer or room conflict
    // Rotate room start position per course to distribute rooms evenly
    const roomOffset = index % ROOMS.length;
    let found = false;
    for (const w of WEEKDAYS) {
      for (const sp of PERIOD_SLOTS) {
        if (scheduleConflicts(lecSched, w, sp, periodCount)) continue;
        for (let ri = 0; ri < ROOMS.length; ri++) {
          const r = ROOMS[(ri + roomOffset) % ROOMS.length];
          if (!roomSchedule.has(r.code)) roomSchedule.set(r.code, []);
          if (scheduleConflicts(roomSchedule.get(r.code)!, w, sp, periodCount))
            continue;
          weekday = w;
          startPeriod = sp;
          roomObj = r;
          found = true;
          break;
        }
        if (found) break;
      }
      if (found) break;
    }

    const slot: SlotEntry = { weekday, startPeriod, periodCount };
    lecSched.push(slot);
    if (!roomSchedule.has(roomObj.code)) roomSchedule.set(roomObj.code, []);
    roomSchedule.get(roomObj.code)!.push(slot);

    return {
      id: `sec-${course.code.toLowerCase()}-1`,
      sectionCode: `${course.code}-1`,
      courseCode: course.code,
      semesterId: currentSemesterId,
      group: "01",
      subGroup: "001",
      lecturerId,
      roomId: roomObj.id,
      room: roomObj.code,
      weekday,
      startPeriod,
      periodCount,
      weeks: "1-15",
      capacity: roomObj.capacity,
      registeredCount: Math.floor(Math.random() * 10),
      waitlistCount: 0,
      allowWaitlist: true,
      status: "OPEN" as const,
      campus: "PTIT HCM",
    };
  });

  // Create in batches of 40 to avoid issues
  for (let i = 0; i < sectionData.length; i += 40) {
    await client.section.createMany({ data: sectionData.slice(i, i + 40) });
  }

  /* ── System Settings ── */
  await client.systemSetting.create({
    data: {
      id: 1,
      simulationNow: new Date("2026-04-10T08:00:00.000Z"),
      registrationStart: new Date("2026-04-01T00:00:00.000Z"),
      registrationEnd: new Date("2026-04-30T23:59:59.999Z"),
      adjustmentStart: new Date("2026-05-01T00:00:00.000Z"),
      adjustmentEnd: new Date("2026-05-10T23:59:59.999Z"),
      maxCreditsMain: 24,
      maxCreditsSummer: 12,
      minCredits: 12,
      maintenanceMode: false,
      allowWaitlist: true,
      countWaitlistCredits: false,
      allowGradeImprovement: true,
      maxRetakeAttempts: 3,
      sessionTimeoutMinutes: 30,
      warningBeforeLogoutSeconds: 60,
      maxClassesPerDay: 4,
      maxClassesPerSemester: 8,
      currentSemesterId,
      maintenanceMessage: "Hệ thống đang hoạt động bình thường.",
    },
  });

  /* ── Student Results (previous semester) ── */
  await client.studentResult.createMany({
    data: [
      {
        id: "result-n23dccn001-int201",
        studentId: "N23DCCN001",
        courseCode: "INT101",
        semesterId: previousSemesterId,
        letterGrade: "B+",
        numericGrade: 8.0,
        status: "PASSED",
        passed: true,
      },
      {
        id: "result-n23dccn001-int203",
        studentId: "N23DCCN001",
        courseCode: "INT102",
        semesterId: previousSemesterId,
        letterGrade: "A",
        numericGrade: 9.0,
        status: "PASSED",
        passed: true,
      },
      {
        id: "result-n23dccn002-int201",
        studentId: "N23DCCN002",
        courseCode: "INT101",
        semesterId: previousSemesterId,
        letterGrade: "C",
        numericGrade: 6.0,
        status: "PASSED",
        passed: true,
      },
      {
        id: "result-n23dcat001-sec201",
        studentId: "N23DCAT001",
        courseCode: "SEC101",
        semesterId: previousSemesterId,
        letterGrade: "B",
        numericGrade: 7.5,
        status: "PASSED",
        passed: true,
      },
      {
        id: "result-n23dcvt001-tel201",
        studentId: "N23DCVT001",
        courseCode: "TEL101",
        semesterId: previousSemesterId,
        letterGrade: "B+",
        numericGrade: 8.0,
        status: "PASSED",
        passed: true,
      },
      {
        id: "result-n23dcdt001-ele201",
        studentId: "N23DCDT001",
        courseCode: "ELE101",
        semesterId: previousSemesterId,
        letterGrade: "A",
        numericGrade: 8.5,
        status: "PASSED",
        passed: true,
      },
    ],
  });

  /* ── Enrollments (current semester) ── */
  await client.enrollment.createMany({
    data: [
      {
        id: "enr-n23dccn001-int204",
        studentId: "N23DCCN001",
        sectionId: "sec-int104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:00:00Z",
            actorId: "N23DCCN001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n23dccn002-int205",
        studentId: "N23DCCN002",
        sectionId: "sec-int105-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:01:00Z",
            actorId: "N23DCCN002",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n23dcat001-sec204",
        studentId: "N23DCAT001",
        sectionId: "sec-sec104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:05:00Z",
            actorId: "N23DCAT001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n23dcvt001-tel204",
        studentId: "N23DCVT001",
        sectionId: "sec-tel104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:10:00Z",
            actorId: "N23DCVT001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n23dcdt001-ele204",
        studentId: "N23DCDT001",
        sectionId: "sec-ele104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:15:00Z",
            actorId: "N23DCDT001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n24dcpt001-mul301",
        studentId: "N24DCPT001",
        sectionId: "sec-mul104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:20:00Z",
            actorId: "N24DCPT001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n24dcqt001-bus301",
        studentId: "N24DCQT001",
        sectionId: "sec-bus104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:25:00Z",
            actorId: "N24DCQT001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n24dcmr001-mkt301",
        studentId: "N24DCMR001",
        sectionId: "sec-mkt104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:30:00Z",
            actorId: "N24DCMR001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
      {
        id: "enr-n24dckt001-acc301",
        studentId: "N24DCKT001",
        sectionId: "sec-acc104-1",
        semesterId: currentSemesterId,
        status: "REGISTERED",
        timeline: [
          {
            status: "REGISTERED",
            timestamp: "2026-04-10T08:35:00Z",
            actorId: "N24DCKT001",
            actorRole: "STUDENT",
            note: "Đăng ký thành công.",
          },
        ],
      },
    ],
  });

  /* ── Wish Requests ── */
  await client.wishRequest.create({
    data: {
      id: "wish-int303-extra",
      studentId: "N23DCCN001",
      semesterId: currentSemesterId,
      courseCode: "INT103",
      preferredGroup: "01",
      reason:
        "Sinh viên có nhu cầu mở thêm lớp Nhập môn CNPM để kịp tiến độ học tập.",
      status: "PENDING",
    },
  });

  /* ── Audit Log ── */
  await client.auditLog.create({
    data: {
      id: "log-seed",
      actorId: "AD001",
      actorRole: "ADMIN",
      action: "SEED_INITIAL_DATA",
      targetId: "SYSTEM",
      result: "SUCCESS",
      message:
        "Tạo dữ liệu demo ban đầu gồm 160 môn, 18 giảng viên, 9 sinh viên.",
      metadata: { seed: "full-catalog-v2" },
    },
  });
}

async function main() {
  const prisma = new PrismaClient();
  try {
    await seedDemoData(prisma, { reset: true });
    console.log(
      "✅ Seed completed: 160 courses, 18 lecturers, 9 students, 160 sections.",
    );
  } finally {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  void main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
