export const REGISTRATION_ERROR_MESSAGES = {
  DK_TC: 'Đăng ký thành công.',
  HUY_DK: 'Đã hủy đăng ký.',
  KHONG_DU_DK: 'Không đủ điều kiện đăng ký.',
  NGOAI_TGDK: 'Ngoài thời gian đăng ký.',
  REG_ERR_SECTION_NOT_OPEN: 'Lớp học phần chưa mở đăng ký.',
  REG_ERR_OUTSIDE_REGISTRATION_WINDOW: 'Ngoài thời gian đăng ký của học kỳ này.',
  REG_ERR_OUTSIDE_ADJUSTMENT_WINDOW: 'Ngoài thời gian điều chỉnh đăng ký.',
  REG_ERR_OUTSIDE_WITHDRAWAL_WINDOW: 'Đã quá hạn rút học phần.',
  REG_ERR_FULL_CAPACITY: 'Lớp học phần đã đủ sĩ số tối đa.',
  REG_ERR_WAITLIST_ONLY: 'Lớp chỉ cho phép vào danh sách chờ.',
  REG_ERR_PREREQUISITE_NOT_MET: 'Sinh viên chưa đạt môn tiên quyết.',
  REG_ERR_PRESTUDY_NOT_MET: 'Sinh viên chưa học môn học trước.',
  REG_ERR_COREQUISITE_NOT_MET: 'Sinh viên chưa đáp ứng môn song hành.',
  REG_ERR_SCHEDULE_CONFLICT: 'Thời khóa biểu bị trùng với học phần đã đăng ký.',
  REG_ERR_CREDIT_LIMIT_EXCEEDED: 'Vượt quá giới hạn số tín chỉ tối đa.',
  REG_ERR_CREDIT_LIMIT_NOT_ENOUGH: 'Chưa đạt ngưỡng tín chỉ tối thiểu của học kỳ.',
  REG_ERR_ALREADY_REGISTERED: 'Sinh viên đã có bản ghi đăng ký cho lớp này.',
  REG_ERR_ALREADY_REGISTERED_COURSE: 'Sinh viên đã đăng ký hoặc vào danh sách chờ một lớp khác của cùng học phần trong học kỳ này.',
  REG_ERR_ALREADY_PASSED: 'Sinh viên đã hoàn thành học phần này.',
  REG_ERR_MAX_RETAKE_EXCEEDED: 'Đã vượt quá số lần học lại cho phép.',
  REG_ERR_CLASS_NOT_FOUND: 'Không tìm thấy lớp học phần.',
  REG_ERR_STUDENT_NOT_FOUND: 'Không tìm thấy thông tin sinh viên.',
  REG_ERR_REGISTRATION_NOT_FOUND: 'Không tìm thấy thông tin đăng ký.',
  REG_ERR_CANNOT_WITHDRAW: 'Không thể hủy hoặc rút học phần này.',
  REG_ERR_CLASS_CANCELLED: 'Lớp học phần đã bị hủy.',
  REG_ERR_ACCOUNT_INACTIVE: 'Tài khoản hiện không thể thực hiện thao tác này.',
  REG_ERR_SYSTEM_ERROR: 'Hệ thống tạm thời không khả dụng.',
  REG_ERR_DATABASE_ERROR: 'Không thể đồng bộ dữ liệu mô phỏng.',
  REG_ERR_PERMISSION_DENIED: 'Người dùng không có quyền thực hiện thao tác.',
  REG_ERR_TIME_CONFLICT_EXAM: 'Trùng lịch thi với học phần khác.',
  REG_ERR_DUPLICATE_REQUEST: 'Yêu cầu đăng ký trùng lặp.',
  REG_ERR_MAX_CLASS_PER_DAY: 'Vượt quá số lớp tối đa trong một ngày.',
  REG_ERR_MAX_CLASS_PER_SEMESTER: 'Vượt quá tổng số lớp tối đa trong học kỳ.',
} as const

export type RegistrationErrorCode = keyof typeof REGISTRATION_ERROR_MESSAGES
